#spring-cloud-starter-netflix-eureka-client
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/